name: ai4business
services:
  notebook:
    image: ai4business-notebook
    build:
      dockerfile: ./dockerfile
    ports:
      - 8888:8888
    volumes:
      - ../notebooks:/tf/ai4business
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
